### ISSUE TITLE
AlmaLinux support status?

### ISSUE THREAD

**Issue by tomgreen66** [ome/ansible-role-selinux-utils#13]
What's the status of using AlmaLinux? Having just installed Omero on AlmaLinux one fix to the Ansible roles was to modify:

```
./ome.selinux_utils/tasks/main.yml
```

Particularly the checking for Rocky:

```
- name: system packages | Add CRB repository for RHEL
  become: true
  ansible.builtin.command:
    subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms    
  when: ansible_os_family == 'RedHat' and not rockyrepo_name.stat.exists
```

How should AlmaLinux behave here?  Is this to add the required repo for the following packages which Rocky doesn't need?  AlmaLinux has CRB via `dnf config-manager --set-enabled crb`

Also wonder whether ansible distribution fact could be used instead (e.g. only when Redhat distribution)?
